[theme]
primaryColor = "#FF334B"
backgroundColor = "#0D0E12"
secondaryBackgroundColor = "#15171F"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
maxUploadSize = 500
maxMessageSize = 200

[browser]
gatherUsageStats = false
